// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: query.proto

package ProtoBufMessages;

public final class QueryProtos {
  private QueryProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface QueryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ProtoBufMessages.Query)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string query = 1;</code>
     */
    java.lang.String getQuery();
    /**
     * <code>string query = 1;</code>
     */
    com.google.protobuf.ByteString
        getQueryBytes();

    /**
     * <code>.ProtoBufMessages.IgnoredInputOutputs ignored_input_outputs = 3;</code>
     */
    boolean hasIgnoredInputOutputs();
    /**
     * <code>.ProtoBufMessages.IgnoredInputOutputs ignored_input_outputs = 3;</code>
     */
    ProtoBufMessages.QueryProtos.IgnoredInputOutputs getIgnoredInputOutputs();
    /**
     * <code>.ProtoBufMessages.IgnoredInputOutputs ignored_input_outputs = 3;</code>
     */
    ProtoBufMessages.QueryProtos.IgnoredInputOutputsOrBuilder getIgnoredInputOutputsOrBuilder();

    /**
     * <code>repeated .ProtoBufMessages.Component components = 4;</code>
     */
    java.util.List<ProtoBufMessages.ComponentProtos.Component> 
        getComponentsList();
    /**
     * <code>repeated .ProtoBufMessages.Component components = 4;</code>
     */
    ProtoBufMessages.ComponentProtos.Component getComponents(int index);
    /**
     * <code>repeated .ProtoBufMessages.Component components = 4;</code>
     */
    int getComponentsCount();
    /**
     * <code>repeated .ProtoBufMessages.Component components = 4;</code>
     */
    java.util.List<? extends ProtoBufMessages.ComponentProtos.ComponentOrBuilder> 
        getComponentsOrBuilderList();
    /**
     * <code>repeated .ProtoBufMessages.Component components = 4;</code>
     */
    ProtoBufMessages.ComponentProtos.ComponentOrBuilder getComponentsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code ProtoBufMessages.Query}
   */
  public  static final class Query extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ProtoBufMessages.Query)
      QueryOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Query.newBuilder() to construct.
    private Query(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Query() {
      query_ = "";
      components_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Query(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              query_ = s;
              break;
            }
            case 26: {
              ProtoBufMessages.QueryProtos.IgnoredInputOutputs.Builder subBuilder = null;
              if (ignoredInputOutputs_ != null) {
                subBuilder = ignoredInputOutputs_.toBuilder();
              }
              ignoredInputOutputs_ = input.readMessage(ProtoBufMessages.QueryProtos.IgnoredInputOutputs.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(ignoredInputOutputs_);
                ignoredInputOutputs_ = subBuilder.buildPartial();
              }

              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                components_ = new java.util.ArrayList<ProtoBufMessages.ComponentProtos.Component>();
                mutable_bitField0_ |= 0x00000004;
              }
              components_.add(
                  input.readMessage(ProtoBufMessages.ComponentProtos.Component.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          components_ = java.util.Collections.unmodifiableList(components_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtoBufMessages.QueryProtos.internal_static_ProtoBufMessages_Query_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtoBufMessages.QueryProtos.internal_static_ProtoBufMessages_Query_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ProtoBufMessages.QueryProtos.Query.class, ProtoBufMessages.QueryProtos.Query.Builder.class);
    }

    private int bitField0_;
    public static final int QUERY_FIELD_NUMBER = 1;
    private volatile java.lang.Object query_;
    /**
     * <code>string query = 1;</code>
     */
    public java.lang.String getQuery() {
      java.lang.Object ref = query_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        query_ = s;
        return s;
      }
    }
    /**
     * <code>string query = 1;</code>
     */
    public com.google.protobuf.ByteString
        getQueryBytes() {
      java.lang.Object ref = query_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        query_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IGNORED_INPUT_OUTPUTS_FIELD_NUMBER = 3;
    private ProtoBufMessages.QueryProtos.IgnoredInputOutputs ignoredInputOutputs_;
    /**
     * <code>.ProtoBufMessages.IgnoredInputOutputs ignored_input_outputs = 3;</code>
     */
    public boolean hasIgnoredInputOutputs() {
      return ignoredInputOutputs_ != null;
    }
    /**
     * <code>.ProtoBufMessages.IgnoredInputOutputs ignored_input_outputs = 3;</code>
     */
    public ProtoBufMessages.QueryProtos.IgnoredInputOutputs getIgnoredInputOutputs() {
      return ignoredInputOutputs_ == null ? ProtoBufMessages.QueryProtos.IgnoredInputOutputs.getDefaultInstance() : ignoredInputOutputs_;
    }
    /**
     * <code>.ProtoBufMessages.IgnoredInputOutputs ignored_input_outputs = 3;</code>
     */
    public ProtoBufMessages.QueryProtos.IgnoredInputOutputsOrBuilder getIgnoredInputOutputsOrBuilder() {
      return getIgnoredInputOutputs();
    }

    public static final int COMPONENTS_FIELD_NUMBER = 4;
    private java.util.List<ProtoBufMessages.ComponentProtos.Component> components_;
    /**
     * <code>repeated .ProtoBufMessages.Component components = 4;</code>
     */
    public java.util.List<ProtoBufMessages.ComponentProtos.Component> getComponentsList() {
      return components_;
    }
    /**
     * <code>repeated .ProtoBufMessages.Component components = 4;</code>
     */
    public java.util.List<? extends ProtoBufMessages.ComponentProtos.ComponentOrBuilder> 
        getComponentsOrBuilderList() {
      return components_;
    }
    /**
     * <code>repeated .ProtoBufMessages.Component components = 4;</code>
     */
    public int getComponentsCount() {
      return components_.size();
    }
    /**
     * <code>repeated .ProtoBufMessages.Component components = 4;</code>
     */
    public ProtoBufMessages.ComponentProtos.Component getComponents(int index) {
      return components_.get(index);
    }
    /**
     * <code>repeated .ProtoBufMessages.Component components = 4;</code>
     */
    public ProtoBufMessages.ComponentProtos.ComponentOrBuilder getComponentsOrBuilder(
        int index) {
      return components_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getQueryBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, query_);
      }
      if (ignoredInputOutputs_ != null) {
        output.writeMessage(3, getIgnoredInputOutputs());
      }
      for (int i = 0; i < components_.size(); i++) {
        output.writeMessage(4, components_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getQueryBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, query_);
      }
      if (ignoredInputOutputs_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getIgnoredInputOutputs());
      }
      for (int i = 0; i < components_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, components_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ProtoBufMessages.QueryProtos.Query)) {
        return super.equals(obj);
      }
      ProtoBufMessages.QueryProtos.Query other = (ProtoBufMessages.QueryProtos.Query) obj;

      boolean result = true;
      result = result && getQuery()
          .equals(other.getQuery());
      result = result && (hasIgnoredInputOutputs() == other.hasIgnoredInputOutputs());
      if (hasIgnoredInputOutputs()) {
        result = result && getIgnoredInputOutputs()
            .equals(other.getIgnoredInputOutputs());
      }
      result = result && getComponentsList()
          .equals(other.getComponentsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + QUERY_FIELD_NUMBER;
      hash = (53 * hash) + getQuery().hashCode();
      if (hasIgnoredInputOutputs()) {
        hash = (37 * hash) + IGNORED_INPUT_OUTPUTS_FIELD_NUMBER;
        hash = (53 * hash) + getIgnoredInputOutputs().hashCode();
      }
      if (getComponentsCount() > 0) {
        hash = (37 * hash) + COMPONENTS_FIELD_NUMBER;
        hash = (53 * hash) + getComponentsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ProtoBufMessages.QueryProtos.Query parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoBufMessages.QueryProtos.Query parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoBufMessages.QueryProtos.Query parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoBufMessages.QueryProtos.Query parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoBufMessages.QueryProtos.Query parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoBufMessages.QueryProtos.Query parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoBufMessages.QueryProtos.Query parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ProtoBufMessages.QueryProtos.Query parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ProtoBufMessages.QueryProtos.Query parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ProtoBufMessages.QueryProtos.Query parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ProtoBufMessages.QueryProtos.Query parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ProtoBufMessages.QueryProtos.Query parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ProtoBufMessages.QueryProtos.Query prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ProtoBufMessages.Query}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ProtoBufMessages.Query)
        ProtoBufMessages.QueryProtos.QueryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoBufMessages.QueryProtos.internal_static_ProtoBufMessages_Query_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoBufMessages.QueryProtos.internal_static_ProtoBufMessages_Query_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ProtoBufMessages.QueryProtos.Query.class, ProtoBufMessages.QueryProtos.Query.Builder.class);
      }

      // Construct using ProtoBufMessages.QueryProtos.Query.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getComponentsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        query_ = "";

        if (ignoredInputOutputsBuilder_ == null) {
          ignoredInputOutputs_ = null;
        } else {
          ignoredInputOutputs_ = null;
          ignoredInputOutputsBuilder_ = null;
        }
        if (componentsBuilder_ == null) {
          components_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          componentsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtoBufMessages.QueryProtos.internal_static_ProtoBufMessages_Query_descriptor;
      }

      @java.lang.Override
      public ProtoBufMessages.QueryProtos.Query getDefaultInstanceForType() {
        return ProtoBufMessages.QueryProtos.Query.getDefaultInstance();
      }

      @java.lang.Override
      public ProtoBufMessages.QueryProtos.Query build() {
        ProtoBufMessages.QueryProtos.Query result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ProtoBufMessages.QueryProtos.Query buildPartial() {
        ProtoBufMessages.QueryProtos.Query result = new ProtoBufMessages.QueryProtos.Query(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.query_ = query_;
        if (ignoredInputOutputsBuilder_ == null) {
          result.ignoredInputOutputs_ = ignoredInputOutputs_;
        } else {
          result.ignoredInputOutputs_ = ignoredInputOutputsBuilder_.build();
        }
        if (componentsBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            components_ = java.util.Collections.unmodifiableList(components_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.components_ = components_;
        } else {
          result.components_ = componentsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ProtoBufMessages.QueryProtos.Query) {
          return mergeFrom((ProtoBufMessages.QueryProtos.Query)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ProtoBufMessages.QueryProtos.Query other) {
        if (other == ProtoBufMessages.QueryProtos.Query.getDefaultInstance()) return this;
        if (!other.getQuery().isEmpty()) {
          query_ = other.query_;
          onChanged();
        }
        if (other.hasIgnoredInputOutputs()) {
          mergeIgnoredInputOutputs(other.getIgnoredInputOutputs());
        }
        if (componentsBuilder_ == null) {
          if (!other.components_.isEmpty()) {
            if (components_.isEmpty()) {
              components_ = other.components_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureComponentsIsMutable();
              components_.addAll(other.components_);
            }
            onChanged();
          }
        } else {
          if (!other.components_.isEmpty()) {
            if (componentsBuilder_.isEmpty()) {
              componentsBuilder_.dispose();
              componentsBuilder_ = null;
              components_ = other.components_;
              bitField0_ = (bitField0_ & ~0x00000004);
              componentsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getComponentsFieldBuilder() : null;
            } else {
              componentsBuilder_.addAllMessages(other.components_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ProtoBufMessages.QueryProtos.Query parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ProtoBufMessages.QueryProtos.Query) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object query_ = "";
      /**
       * <code>string query = 1;</code>
       */
      public java.lang.String getQuery() {
        java.lang.Object ref = query_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          query_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string query = 1;</code>
       */
      public com.google.protobuf.ByteString
          getQueryBytes() {
        java.lang.Object ref = query_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          query_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string query = 1;</code>
       */
      public Builder setQuery(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        query_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string query = 1;</code>
       */
      public Builder clearQuery() {
        
        query_ = getDefaultInstance().getQuery();
        onChanged();
        return this;
      }
      /**
       * <code>string query = 1;</code>
       */
      public Builder setQueryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        query_ = value;
        onChanged();
        return this;
      }

      private ProtoBufMessages.QueryProtos.IgnoredInputOutputs ignoredInputOutputs_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          ProtoBufMessages.QueryProtos.IgnoredInputOutputs, ProtoBufMessages.QueryProtos.IgnoredInputOutputs.Builder, ProtoBufMessages.QueryProtos.IgnoredInputOutputsOrBuilder> ignoredInputOutputsBuilder_;
      /**
       * <code>.ProtoBufMessages.IgnoredInputOutputs ignored_input_outputs = 3;</code>
       */
      public boolean hasIgnoredInputOutputs() {
        return ignoredInputOutputsBuilder_ != null || ignoredInputOutputs_ != null;
      }
      /**
       * <code>.ProtoBufMessages.IgnoredInputOutputs ignored_input_outputs = 3;</code>
       */
      public ProtoBufMessages.QueryProtos.IgnoredInputOutputs getIgnoredInputOutputs() {
        if (ignoredInputOutputsBuilder_ == null) {
          return ignoredInputOutputs_ == null ? ProtoBufMessages.QueryProtos.IgnoredInputOutputs.getDefaultInstance() : ignoredInputOutputs_;
        } else {
          return ignoredInputOutputsBuilder_.getMessage();
        }
      }
      /**
       * <code>.ProtoBufMessages.IgnoredInputOutputs ignored_input_outputs = 3;</code>
       */
      public Builder setIgnoredInputOutputs(ProtoBufMessages.QueryProtos.IgnoredInputOutputs value) {
        if (ignoredInputOutputsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ignoredInputOutputs_ = value;
          onChanged();
        } else {
          ignoredInputOutputsBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.ProtoBufMessages.IgnoredInputOutputs ignored_input_outputs = 3;</code>
       */
      public Builder setIgnoredInputOutputs(
          ProtoBufMessages.QueryProtos.IgnoredInputOutputs.Builder builderForValue) {
        if (ignoredInputOutputsBuilder_ == null) {
          ignoredInputOutputs_ = builderForValue.build();
          onChanged();
        } else {
          ignoredInputOutputsBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.ProtoBufMessages.IgnoredInputOutputs ignored_input_outputs = 3;</code>
       */
      public Builder mergeIgnoredInputOutputs(ProtoBufMessages.QueryProtos.IgnoredInputOutputs value) {
        if (ignoredInputOutputsBuilder_ == null) {
          if (ignoredInputOutputs_ != null) {
            ignoredInputOutputs_ =
              ProtoBufMessages.QueryProtos.IgnoredInputOutputs.newBuilder(ignoredInputOutputs_).mergeFrom(value).buildPartial();
          } else {
            ignoredInputOutputs_ = value;
          }
          onChanged();
        } else {
          ignoredInputOutputsBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.ProtoBufMessages.IgnoredInputOutputs ignored_input_outputs = 3;</code>
       */
      public Builder clearIgnoredInputOutputs() {
        if (ignoredInputOutputsBuilder_ == null) {
          ignoredInputOutputs_ = null;
          onChanged();
        } else {
          ignoredInputOutputs_ = null;
          ignoredInputOutputsBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.ProtoBufMessages.IgnoredInputOutputs ignored_input_outputs = 3;</code>
       */
      public ProtoBufMessages.QueryProtos.IgnoredInputOutputs.Builder getIgnoredInputOutputsBuilder() {
        
        onChanged();
        return getIgnoredInputOutputsFieldBuilder().getBuilder();
      }
      /**
       * <code>.ProtoBufMessages.IgnoredInputOutputs ignored_input_outputs = 3;</code>
       */
      public ProtoBufMessages.QueryProtos.IgnoredInputOutputsOrBuilder getIgnoredInputOutputsOrBuilder() {
        if (ignoredInputOutputsBuilder_ != null) {
          return ignoredInputOutputsBuilder_.getMessageOrBuilder();
        } else {
          return ignoredInputOutputs_ == null ?
              ProtoBufMessages.QueryProtos.IgnoredInputOutputs.getDefaultInstance() : ignoredInputOutputs_;
        }
      }
      /**
       * <code>.ProtoBufMessages.IgnoredInputOutputs ignored_input_outputs = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          ProtoBufMessages.QueryProtos.IgnoredInputOutputs, ProtoBufMessages.QueryProtos.IgnoredInputOutputs.Builder, ProtoBufMessages.QueryProtos.IgnoredInputOutputsOrBuilder> 
          getIgnoredInputOutputsFieldBuilder() {
        if (ignoredInputOutputsBuilder_ == null) {
          ignoredInputOutputsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              ProtoBufMessages.QueryProtos.IgnoredInputOutputs, ProtoBufMessages.QueryProtos.IgnoredInputOutputs.Builder, ProtoBufMessages.QueryProtos.IgnoredInputOutputsOrBuilder>(
                  getIgnoredInputOutputs(),
                  getParentForChildren(),
                  isClean());
          ignoredInputOutputs_ = null;
        }
        return ignoredInputOutputsBuilder_;
      }

      private java.util.List<ProtoBufMessages.ComponentProtos.Component> components_ =
        java.util.Collections.emptyList();
      private void ensureComponentsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          components_ = new java.util.ArrayList<ProtoBufMessages.ComponentProtos.Component>(components_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          ProtoBufMessages.ComponentProtos.Component, ProtoBufMessages.ComponentProtos.Component.Builder, ProtoBufMessages.ComponentProtos.ComponentOrBuilder> componentsBuilder_;

      /**
       * <code>repeated .ProtoBufMessages.Component components = 4;</code>
       */
      public java.util.List<ProtoBufMessages.ComponentProtos.Component> getComponentsList() {
        if (componentsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(components_);
        } else {
          return componentsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .ProtoBufMessages.Component components = 4;</code>
       */
      public int getComponentsCount() {
        if (componentsBuilder_ == null) {
          return components_.size();
        } else {
          return componentsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .ProtoBufMessages.Component components = 4;</code>
       */
      public ProtoBufMessages.ComponentProtos.Component getComponents(int index) {
        if (componentsBuilder_ == null) {
          return components_.get(index);
        } else {
          return componentsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .ProtoBufMessages.Component components = 4;</code>
       */
      public Builder setComponents(
          int index, ProtoBufMessages.ComponentProtos.Component value) {
        if (componentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureComponentsIsMutable();
          components_.set(index, value);
          onChanged();
        } else {
          componentsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ProtoBufMessages.Component components = 4;</code>
       */
      public Builder setComponents(
          int index, ProtoBufMessages.ComponentProtos.Component.Builder builderForValue) {
        if (componentsBuilder_ == null) {
          ensureComponentsIsMutable();
          components_.set(index, builderForValue.build());
          onChanged();
        } else {
          componentsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ProtoBufMessages.Component components = 4;</code>
       */
      public Builder addComponents(ProtoBufMessages.ComponentProtos.Component value) {
        if (componentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureComponentsIsMutable();
          components_.add(value);
          onChanged();
        } else {
          componentsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .ProtoBufMessages.Component components = 4;</code>
       */
      public Builder addComponents(
          int index, ProtoBufMessages.ComponentProtos.Component value) {
        if (componentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureComponentsIsMutable();
          components_.add(index, value);
          onChanged();
        } else {
          componentsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ProtoBufMessages.Component components = 4;</code>
       */
      public Builder addComponents(
          ProtoBufMessages.ComponentProtos.Component.Builder builderForValue) {
        if (componentsBuilder_ == null) {
          ensureComponentsIsMutable();
          components_.add(builderForValue.build());
          onChanged();
        } else {
          componentsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ProtoBufMessages.Component components = 4;</code>
       */
      public Builder addComponents(
          int index, ProtoBufMessages.ComponentProtos.Component.Builder builderForValue) {
        if (componentsBuilder_ == null) {
          ensureComponentsIsMutable();
          components_.add(index, builderForValue.build());
          onChanged();
        } else {
          componentsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ProtoBufMessages.Component components = 4;</code>
       */
      public Builder addAllComponents(
          java.lang.Iterable<? extends ProtoBufMessages.ComponentProtos.Component> values) {
        if (componentsBuilder_ == null) {
          ensureComponentsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, components_);
          onChanged();
        } else {
          componentsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .ProtoBufMessages.Component components = 4;</code>
       */
      public Builder clearComponents() {
        if (componentsBuilder_ == null) {
          components_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          componentsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .ProtoBufMessages.Component components = 4;</code>
       */
      public Builder removeComponents(int index) {
        if (componentsBuilder_ == null) {
          ensureComponentsIsMutable();
          components_.remove(index);
          onChanged();
        } else {
          componentsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .ProtoBufMessages.Component components = 4;</code>
       */
      public ProtoBufMessages.ComponentProtos.Component.Builder getComponentsBuilder(
          int index) {
        return getComponentsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .ProtoBufMessages.Component components = 4;</code>
       */
      public ProtoBufMessages.ComponentProtos.ComponentOrBuilder getComponentsOrBuilder(
          int index) {
        if (componentsBuilder_ == null) {
          return components_.get(index);  } else {
          return componentsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .ProtoBufMessages.Component components = 4;</code>
       */
      public java.util.List<? extends ProtoBufMessages.ComponentProtos.ComponentOrBuilder> 
           getComponentsOrBuilderList() {
        if (componentsBuilder_ != null) {
          return componentsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(components_);
        }
      }
      /**
       * <code>repeated .ProtoBufMessages.Component components = 4;</code>
       */
      public ProtoBufMessages.ComponentProtos.Component.Builder addComponentsBuilder() {
        return getComponentsFieldBuilder().addBuilder(
            ProtoBufMessages.ComponentProtos.Component.getDefaultInstance());
      }
      /**
       * <code>repeated .ProtoBufMessages.Component components = 4;</code>
       */
      public ProtoBufMessages.ComponentProtos.Component.Builder addComponentsBuilder(
          int index) {
        return getComponentsFieldBuilder().addBuilder(
            index, ProtoBufMessages.ComponentProtos.Component.getDefaultInstance());
      }
      /**
       * <code>repeated .ProtoBufMessages.Component components = 4;</code>
       */
      public java.util.List<ProtoBufMessages.ComponentProtos.Component.Builder> 
           getComponentsBuilderList() {
        return getComponentsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          ProtoBufMessages.ComponentProtos.Component, ProtoBufMessages.ComponentProtos.Component.Builder, ProtoBufMessages.ComponentProtos.ComponentOrBuilder> 
          getComponentsFieldBuilder() {
        if (componentsBuilder_ == null) {
          componentsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              ProtoBufMessages.ComponentProtos.Component, ProtoBufMessages.ComponentProtos.Component.Builder, ProtoBufMessages.ComponentProtos.ComponentOrBuilder>(
                  components_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          components_ = null;
        }
        return componentsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ProtoBufMessages.Query)
    }

    // @@protoc_insertion_point(class_scope:ProtoBufMessages.Query)
    private static final ProtoBufMessages.QueryProtos.Query DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ProtoBufMessages.QueryProtos.Query();
    }

    public static ProtoBufMessages.QueryProtos.Query getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Query>
        PARSER = new com.google.protobuf.AbstractParser<Query>() {
      @java.lang.Override
      public Query parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Query(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Query> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Query> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ProtoBufMessages.QueryProtos.Query getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface IgnoredInputOutputsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ProtoBufMessages.IgnoredInputOutputs)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated string ignored_inputs = 1;</code>
     */
    java.util.List<java.lang.String>
        getIgnoredInputsList();
    /**
     * <code>repeated string ignored_inputs = 1;</code>
     */
    int getIgnoredInputsCount();
    /**
     * <code>repeated string ignored_inputs = 1;</code>
     */
    java.lang.String getIgnoredInputs(int index);
    /**
     * <code>repeated string ignored_inputs = 1;</code>
     */
    com.google.protobuf.ByteString
        getIgnoredInputsBytes(int index);

    /**
     * <code>repeated string ignored_outputs = 2;</code>
     */
    java.util.List<java.lang.String>
        getIgnoredOutputsList();
    /**
     * <code>repeated string ignored_outputs = 2;</code>
     */
    int getIgnoredOutputsCount();
    /**
     * <code>repeated string ignored_outputs = 2;</code>
     */
    java.lang.String getIgnoredOutputs(int index);
    /**
     * <code>repeated string ignored_outputs = 2;</code>
     */
    com.google.protobuf.ByteString
        getIgnoredOutputsBytes(int index);
  }
  /**
   * Protobuf type {@code ProtoBufMessages.IgnoredInputOutputs}
   */
  public  static final class IgnoredInputOutputs extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ProtoBufMessages.IgnoredInputOutputs)
      IgnoredInputOutputsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use IgnoredInputOutputs.newBuilder() to construct.
    private IgnoredInputOutputs(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private IgnoredInputOutputs() {
      ignoredInputs_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      ignoredOutputs_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private IgnoredInputOutputs(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                ignoredInputs_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              ignoredInputs_.add(s);
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                ignoredOutputs_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              ignoredOutputs_.add(s);
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          ignoredInputs_ = ignoredInputs_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          ignoredOutputs_ = ignoredOutputs_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtoBufMessages.QueryProtos.internal_static_ProtoBufMessages_IgnoredInputOutputs_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtoBufMessages.QueryProtos.internal_static_ProtoBufMessages_IgnoredInputOutputs_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ProtoBufMessages.QueryProtos.IgnoredInputOutputs.class, ProtoBufMessages.QueryProtos.IgnoredInputOutputs.Builder.class);
    }

    public static final int IGNORED_INPUTS_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList ignoredInputs_;
    /**
     * <code>repeated string ignored_inputs = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getIgnoredInputsList() {
      return ignoredInputs_;
    }
    /**
     * <code>repeated string ignored_inputs = 1;</code>
     */
    public int getIgnoredInputsCount() {
      return ignoredInputs_.size();
    }
    /**
     * <code>repeated string ignored_inputs = 1;</code>
     */
    public java.lang.String getIgnoredInputs(int index) {
      return ignoredInputs_.get(index);
    }
    /**
     * <code>repeated string ignored_inputs = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIgnoredInputsBytes(int index) {
      return ignoredInputs_.getByteString(index);
    }

    public static final int IGNORED_OUTPUTS_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList ignoredOutputs_;
    /**
     * <code>repeated string ignored_outputs = 2;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getIgnoredOutputsList() {
      return ignoredOutputs_;
    }
    /**
     * <code>repeated string ignored_outputs = 2;</code>
     */
    public int getIgnoredOutputsCount() {
      return ignoredOutputs_.size();
    }
    /**
     * <code>repeated string ignored_outputs = 2;</code>
     */
    public java.lang.String getIgnoredOutputs(int index) {
      return ignoredOutputs_.get(index);
    }
    /**
     * <code>repeated string ignored_outputs = 2;</code>
     */
    public com.google.protobuf.ByteString
        getIgnoredOutputsBytes(int index) {
      return ignoredOutputs_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < ignoredInputs_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, ignoredInputs_.getRaw(i));
      }
      for (int i = 0; i < ignoredOutputs_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, ignoredOutputs_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < ignoredInputs_.size(); i++) {
          dataSize += computeStringSizeNoTag(ignoredInputs_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getIgnoredInputsList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < ignoredOutputs_.size(); i++) {
          dataSize += computeStringSizeNoTag(ignoredOutputs_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getIgnoredOutputsList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ProtoBufMessages.QueryProtos.IgnoredInputOutputs)) {
        return super.equals(obj);
      }
      ProtoBufMessages.QueryProtos.IgnoredInputOutputs other = (ProtoBufMessages.QueryProtos.IgnoredInputOutputs) obj;

      boolean result = true;
      result = result && getIgnoredInputsList()
          .equals(other.getIgnoredInputsList());
      result = result && getIgnoredOutputsList()
          .equals(other.getIgnoredOutputsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getIgnoredInputsCount() > 0) {
        hash = (37 * hash) + IGNORED_INPUTS_FIELD_NUMBER;
        hash = (53 * hash) + getIgnoredInputsList().hashCode();
      }
      if (getIgnoredOutputsCount() > 0) {
        hash = (37 * hash) + IGNORED_OUTPUTS_FIELD_NUMBER;
        hash = (53 * hash) + getIgnoredOutputsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ProtoBufMessages.QueryProtos.IgnoredInputOutputs parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoBufMessages.QueryProtos.IgnoredInputOutputs parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoBufMessages.QueryProtos.IgnoredInputOutputs parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoBufMessages.QueryProtos.IgnoredInputOutputs parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoBufMessages.QueryProtos.IgnoredInputOutputs parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoBufMessages.QueryProtos.IgnoredInputOutputs parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoBufMessages.QueryProtos.IgnoredInputOutputs parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ProtoBufMessages.QueryProtos.IgnoredInputOutputs parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ProtoBufMessages.QueryProtos.IgnoredInputOutputs parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ProtoBufMessages.QueryProtos.IgnoredInputOutputs parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ProtoBufMessages.QueryProtos.IgnoredInputOutputs parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ProtoBufMessages.QueryProtos.IgnoredInputOutputs parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ProtoBufMessages.QueryProtos.IgnoredInputOutputs prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ProtoBufMessages.IgnoredInputOutputs}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ProtoBufMessages.IgnoredInputOutputs)
        ProtoBufMessages.QueryProtos.IgnoredInputOutputsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoBufMessages.QueryProtos.internal_static_ProtoBufMessages_IgnoredInputOutputs_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoBufMessages.QueryProtos.internal_static_ProtoBufMessages_IgnoredInputOutputs_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ProtoBufMessages.QueryProtos.IgnoredInputOutputs.class, ProtoBufMessages.QueryProtos.IgnoredInputOutputs.Builder.class);
      }

      // Construct using ProtoBufMessages.QueryProtos.IgnoredInputOutputs.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        ignoredInputs_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        ignoredOutputs_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtoBufMessages.QueryProtos.internal_static_ProtoBufMessages_IgnoredInputOutputs_descriptor;
      }

      @java.lang.Override
      public ProtoBufMessages.QueryProtos.IgnoredInputOutputs getDefaultInstanceForType() {
        return ProtoBufMessages.QueryProtos.IgnoredInputOutputs.getDefaultInstance();
      }

      @java.lang.Override
      public ProtoBufMessages.QueryProtos.IgnoredInputOutputs build() {
        ProtoBufMessages.QueryProtos.IgnoredInputOutputs result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ProtoBufMessages.QueryProtos.IgnoredInputOutputs buildPartial() {
        ProtoBufMessages.QueryProtos.IgnoredInputOutputs result = new ProtoBufMessages.QueryProtos.IgnoredInputOutputs(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          ignoredInputs_ = ignoredInputs_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.ignoredInputs_ = ignoredInputs_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          ignoredOutputs_ = ignoredOutputs_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.ignoredOutputs_ = ignoredOutputs_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ProtoBufMessages.QueryProtos.IgnoredInputOutputs) {
          return mergeFrom((ProtoBufMessages.QueryProtos.IgnoredInputOutputs)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ProtoBufMessages.QueryProtos.IgnoredInputOutputs other) {
        if (other == ProtoBufMessages.QueryProtos.IgnoredInputOutputs.getDefaultInstance()) return this;
        if (!other.ignoredInputs_.isEmpty()) {
          if (ignoredInputs_.isEmpty()) {
            ignoredInputs_ = other.ignoredInputs_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureIgnoredInputsIsMutable();
            ignoredInputs_.addAll(other.ignoredInputs_);
          }
          onChanged();
        }
        if (!other.ignoredOutputs_.isEmpty()) {
          if (ignoredOutputs_.isEmpty()) {
            ignoredOutputs_ = other.ignoredOutputs_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureIgnoredOutputsIsMutable();
            ignoredOutputs_.addAll(other.ignoredOutputs_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ProtoBufMessages.QueryProtos.IgnoredInputOutputs parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ProtoBufMessages.QueryProtos.IgnoredInputOutputs) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringList ignoredInputs_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureIgnoredInputsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          ignoredInputs_ = new com.google.protobuf.LazyStringArrayList(ignoredInputs_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string ignored_inputs = 1;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getIgnoredInputsList() {
        return ignoredInputs_.getUnmodifiableView();
      }
      /**
       * <code>repeated string ignored_inputs = 1;</code>
       */
      public int getIgnoredInputsCount() {
        return ignoredInputs_.size();
      }
      /**
       * <code>repeated string ignored_inputs = 1;</code>
       */
      public java.lang.String getIgnoredInputs(int index) {
        return ignoredInputs_.get(index);
      }
      /**
       * <code>repeated string ignored_inputs = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIgnoredInputsBytes(int index) {
        return ignoredInputs_.getByteString(index);
      }
      /**
       * <code>repeated string ignored_inputs = 1;</code>
       */
      public Builder setIgnoredInputs(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureIgnoredInputsIsMutable();
        ignoredInputs_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string ignored_inputs = 1;</code>
       */
      public Builder addIgnoredInputs(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureIgnoredInputsIsMutable();
        ignoredInputs_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string ignored_inputs = 1;</code>
       */
      public Builder addAllIgnoredInputs(
          java.lang.Iterable<java.lang.String> values) {
        ensureIgnoredInputsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, ignoredInputs_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string ignored_inputs = 1;</code>
       */
      public Builder clearIgnoredInputs() {
        ignoredInputs_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string ignored_inputs = 1;</code>
       */
      public Builder addIgnoredInputsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureIgnoredInputsIsMutable();
        ignoredInputs_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList ignoredOutputs_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureIgnoredOutputsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          ignoredOutputs_ = new com.google.protobuf.LazyStringArrayList(ignoredOutputs_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string ignored_outputs = 2;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getIgnoredOutputsList() {
        return ignoredOutputs_.getUnmodifiableView();
      }
      /**
       * <code>repeated string ignored_outputs = 2;</code>
       */
      public int getIgnoredOutputsCount() {
        return ignoredOutputs_.size();
      }
      /**
       * <code>repeated string ignored_outputs = 2;</code>
       */
      public java.lang.String getIgnoredOutputs(int index) {
        return ignoredOutputs_.get(index);
      }
      /**
       * <code>repeated string ignored_outputs = 2;</code>
       */
      public com.google.protobuf.ByteString
          getIgnoredOutputsBytes(int index) {
        return ignoredOutputs_.getByteString(index);
      }
      /**
       * <code>repeated string ignored_outputs = 2;</code>
       */
      public Builder setIgnoredOutputs(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureIgnoredOutputsIsMutable();
        ignoredOutputs_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string ignored_outputs = 2;</code>
       */
      public Builder addIgnoredOutputs(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureIgnoredOutputsIsMutable();
        ignoredOutputs_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string ignored_outputs = 2;</code>
       */
      public Builder addAllIgnoredOutputs(
          java.lang.Iterable<java.lang.String> values) {
        ensureIgnoredOutputsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, ignoredOutputs_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string ignored_outputs = 2;</code>
       */
      public Builder clearIgnoredOutputs() {
        ignoredOutputs_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string ignored_outputs = 2;</code>
       */
      public Builder addIgnoredOutputsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureIgnoredOutputsIsMutable();
        ignoredOutputs_.add(value);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ProtoBufMessages.IgnoredInputOutputs)
    }

    // @@protoc_insertion_point(class_scope:ProtoBufMessages.IgnoredInputOutputs)
    private static final ProtoBufMessages.QueryProtos.IgnoredInputOutputs DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ProtoBufMessages.QueryProtos.IgnoredInputOutputs();
    }

    public static ProtoBufMessages.QueryProtos.IgnoredInputOutputs getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<IgnoredInputOutputs>
        PARSER = new com.google.protobuf.AbstractParser<IgnoredInputOutputs>() {
      @java.lang.Override
      public IgnoredInputOutputs parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new IgnoredInputOutputs(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<IgnoredInputOutputs> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<IgnoredInputOutputs> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ProtoBufMessages.QueryProtos.IgnoredInputOutputs getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtoBufMessages_Query_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProtoBufMessages_Query_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtoBufMessages_IgnoredInputOutputs_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProtoBufMessages_IgnoredInputOutputs_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013query.proto\022\020ProtoBufMessages\032\017compone" +
      "nt.proto\"\215\001\n\005Query\022\r\n\005query\030\001 \001(\t\022D\n\025ign" +
      "ored_input_outputs\030\003 \001(\0132%.ProtoBufMessa" +
      "ges.IgnoredInputOutputs\022/\n\ncomponents\030\004 " +
      "\003(\0132\033.ProtoBufMessages.Component\"F\n\023Igno" +
      "redInputOutputs\022\026\n\016ignored_inputs\030\001 \003(\t\022" +
      "\027\n\017ignored_outputs\030\002 \003(\tB!\n\020ProtoBufMess" +
      "agesB\013QueryProtosP\000b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ProtoBufMessages.ComponentProtos.getDescriptor(),
        }, assigner);
    internal_static_ProtoBufMessages_Query_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ProtoBufMessages_Query_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProtoBufMessages_Query_descriptor,
        new java.lang.String[] { "Query", "IgnoredInputOutputs", "Components", });
    internal_static_ProtoBufMessages_IgnoredInputOutputs_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ProtoBufMessages_IgnoredInputOutputs_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProtoBufMessages_IgnoredInputOutputs_descriptor,
        new java.lang.String[] { "IgnoredInputs", "IgnoredOutputs", });
    ProtoBufMessages.ComponentProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
