//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: query.proto

package EcdarProtoBuf;

@kotlin.jvm.JvmSynthetic
inline fun componentsUpdateRequest(block: EcdarProtoBuf.ComponentsUpdateRequestKt.Dsl.() -> kotlin.Unit): EcdarProtoBuf.QueryProtos.ComponentsUpdateRequest =
  EcdarProtoBuf.ComponentsUpdateRequestKt.Dsl._create(EcdarProtoBuf.QueryProtos.ComponentsUpdateRequest.newBuilder()).apply { block() }._build()
object ComponentsUpdateRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: EcdarProtoBuf.QueryProtos.ComponentsUpdateRequest.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: EcdarProtoBuf.QueryProtos.ComponentsUpdateRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): EcdarProtoBuf.QueryProtos.ComponentsUpdateRequest = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    class ComponentsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated .EcdarProtoBuf.Component components = 2;</code>
     */
     val components: com.google.protobuf.kotlin.DslList<EcdarProtoBuf.ComponentProtos.Component, ComponentsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getComponentsList()
      )
    /**
     * <code>repeated .EcdarProtoBuf.Component components = 2;</code>
     * @param value The components to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addComponents")
    fun com.google.protobuf.kotlin.DslList<EcdarProtoBuf.ComponentProtos.Component, ComponentsProxy>.add(value: EcdarProtoBuf.ComponentProtos.Component) {
      _builder.addComponents(value)
    }/**
     * <code>repeated .EcdarProtoBuf.Component components = 2;</code>
     * @param value The components to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignComponents")
    inline operator fun com.google.protobuf.kotlin.DslList<EcdarProtoBuf.ComponentProtos.Component, ComponentsProxy>.plusAssign(value: EcdarProtoBuf.ComponentProtos.Component) {
      add(value)
    }/**
     * <code>repeated .EcdarProtoBuf.Component components = 2;</code>
     * @param values The components to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllComponents")
    fun com.google.protobuf.kotlin.DslList<EcdarProtoBuf.ComponentProtos.Component, ComponentsProxy>.addAll(values: kotlin.collections.Iterable<EcdarProtoBuf.ComponentProtos.Component>) {
      _builder.addAllComponents(values)
    }/**
     * <code>repeated .EcdarProtoBuf.Component components = 2;</code>
     * @param values The components to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllComponents")
    inline operator fun com.google.protobuf.kotlin.DslList<EcdarProtoBuf.ComponentProtos.Component, ComponentsProxy>.plusAssign(values: kotlin.collections.Iterable<EcdarProtoBuf.ComponentProtos.Component>) {
      addAll(values)
    }/**
     * <code>repeated .EcdarProtoBuf.Component components = 2;</code>
     * @param index The index to set the value at.
     * @param value The components to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setComponents")
    operator fun com.google.protobuf.kotlin.DslList<EcdarProtoBuf.ComponentProtos.Component, ComponentsProxy>.set(index: kotlin.Int, value: EcdarProtoBuf.ComponentProtos.Component) {
      _builder.setComponents(index, value)
    }/**
     * <code>repeated .EcdarProtoBuf.Component components = 2;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearComponents")
    fun com.google.protobuf.kotlin.DslList<EcdarProtoBuf.ComponentProtos.Component, ComponentsProxy>.clear() {
      _builder.clearComponents()
    }
    /**
     * <pre>
     * hash
     * </pre>
     *
     * <code>int32 etag = 3;</code>
     */
    var etag: kotlin.Int
      @JvmName("getEtag")
      get() = _builder.getEtag()
      @JvmName("setEtag")
      set(value) {
        _builder.setEtag(value)
      }
    /**
     * <pre>
     * hash
     * </pre>
     *
     * <code>int32 etag = 3;</code>
     */
    fun clearEtag() {
      _builder.clearEtag()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun EcdarProtoBuf.QueryProtos.ComponentsUpdateRequest.copy(block: EcdarProtoBuf.ComponentsUpdateRequestKt.Dsl.() -> kotlin.Unit): EcdarProtoBuf.QueryProtos.ComponentsUpdateRequest =
  EcdarProtoBuf.ComponentsUpdateRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()
