//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: query.proto

package EcdarProtoBuf;

@kotlin.jvm.JvmSynthetic
inline fun ignoredInputOutputs(block: EcdarProtoBuf.IgnoredInputOutputsKt.Dsl.() -> kotlin.Unit): EcdarProtoBuf.QueryProtos.IgnoredInputOutputs =
  EcdarProtoBuf.IgnoredInputOutputsKt.Dsl._create(EcdarProtoBuf.QueryProtos.IgnoredInputOutputs.newBuilder()).apply { block() }._build()
object IgnoredInputOutputsKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: EcdarProtoBuf.QueryProtos.IgnoredInputOutputs.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: EcdarProtoBuf.QueryProtos.IgnoredInputOutputs.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): EcdarProtoBuf.QueryProtos.IgnoredInputOutputs = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    class IgnoredInputsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated string ignored_inputs = 1;</code>
     * @return A list containing the ignoredInputs.
     */
    val ignoredInputs: com.google.protobuf.kotlin.DslList<kotlin.String, IgnoredInputsProxy>
      @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getIgnoredInputsList()
      )
    /**
     * <code>repeated string ignored_inputs = 1;</code>
     * @param value The ignoredInputs to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addIgnoredInputs")
    fun com.google.protobuf.kotlin.DslList<kotlin.String, IgnoredInputsProxy>.add(value: kotlin.String) {
      _builder.addIgnoredInputs(value)
    }
    /**
     * <code>repeated string ignored_inputs = 1;</code>
     * @param value The ignoredInputs to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignIgnoredInputs")
    operator fun com.google.protobuf.kotlin.DslList<kotlin.String, IgnoredInputsProxy>.plusAssign(value: kotlin.String) {
      _builder.addIgnoredInputs(value)
    }
    /**
     * <code>repeated string ignored_inputs = 1;</code>
     * @param values The ignoredInputs to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllIgnoredInputs")
    fun com.google.protobuf.kotlin.DslList<kotlin.String, IgnoredInputsProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllIgnoredInputs(values)
    }
    /**
     * <code>repeated string ignored_inputs = 1;</code>
     * @param values The ignoredInputs to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllIgnoredInputs")
    operator fun com.google.protobuf.kotlin.DslList<kotlin.String, IgnoredInputsProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllIgnoredInputs(values)
    }
    /**
     * <code>repeated string ignored_inputs = 1;</code>
     * @param index The index to set the value at.
     * @param value The ignoredInputs to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setIgnoredInputs")
    operator fun com.google.protobuf.kotlin.DslList<kotlin.String, IgnoredInputsProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setIgnoredInputs(index, value)
    }/**
     * <code>repeated string ignored_inputs = 1;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearIgnoredInputs")
    fun com.google.protobuf.kotlin.DslList<kotlin.String, IgnoredInputsProxy>.clear() {
      _builder.clearIgnoredInputs()
    }
    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    class IgnoredOutputsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated string ignored_outputs = 2;</code>
     * @return A list containing the ignoredOutputs.
     */
    val ignoredOutputs: com.google.protobuf.kotlin.DslList<kotlin.String, IgnoredOutputsProxy>
      @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getIgnoredOutputsList()
      )
    /**
     * <code>repeated string ignored_outputs = 2;</code>
     * @param value The ignoredOutputs to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addIgnoredOutputs")
    fun com.google.protobuf.kotlin.DslList<kotlin.String, IgnoredOutputsProxy>.add(value: kotlin.String) {
      _builder.addIgnoredOutputs(value)
    }
    /**
     * <code>repeated string ignored_outputs = 2;</code>
     * @param value The ignoredOutputs to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignIgnoredOutputs")
    operator fun com.google.protobuf.kotlin.DslList<kotlin.String, IgnoredOutputsProxy>.plusAssign(value: kotlin.String) {
      _builder.addIgnoredOutputs(value)
    }
    /**
     * <code>repeated string ignored_outputs = 2;</code>
     * @param values The ignoredOutputs to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllIgnoredOutputs")
    fun com.google.protobuf.kotlin.DslList<kotlin.String, IgnoredOutputsProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllIgnoredOutputs(values)
    }
    /**
     * <code>repeated string ignored_outputs = 2;</code>
     * @param values The ignoredOutputs to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllIgnoredOutputs")
    operator fun com.google.protobuf.kotlin.DslList<kotlin.String, IgnoredOutputsProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllIgnoredOutputs(values)
    }
    /**
     * <code>repeated string ignored_outputs = 2;</code>
     * @param index The index to set the value at.
     * @param value The ignoredOutputs to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setIgnoredOutputs")
    operator fun com.google.protobuf.kotlin.DslList<kotlin.String, IgnoredOutputsProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setIgnoredOutputs(index, value)
    }/**
     * <code>repeated string ignored_outputs = 2;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearIgnoredOutputs")
    fun com.google.protobuf.kotlin.DslList<kotlin.String, IgnoredOutputsProxy>.clear() {
      _builder.clearIgnoredOutputs()
    }}
}
@kotlin.jvm.JvmSynthetic
inline fun EcdarProtoBuf.QueryProtos.IgnoredInputOutputs.copy(block: EcdarProtoBuf.IgnoredInputOutputsKt.Dsl.() -> kotlin.Unit): EcdarProtoBuf.QueryProtos.IgnoredInputOutputs =
  EcdarProtoBuf.IgnoredInputOutputsKt.Dsl._create(this.toBuilder()).apply { block() }._build()
