//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: query.proto

package EcdarProtoBuf;

@kotlin.jvm.JvmSynthetic
inline fun queryRequest(block: EcdarProtoBuf.QueryRequestKt.Dsl.() -> kotlin.Unit): EcdarProtoBuf.QueryProtos.QueryRequest =
  EcdarProtoBuf.QueryRequestKt.Dsl._create(EcdarProtoBuf.QueryProtos.QueryRequest.newBuilder()).apply { block() }._build()
object QueryRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: EcdarProtoBuf.QueryProtos.QueryRequest.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: EcdarProtoBuf.QueryProtos.QueryRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): EcdarProtoBuf.QueryProtos.QueryRequest = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    class QueriesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <pre>
     * repeated string extra i/o
     * </pre>
     *
     * <code>repeated .EcdarProtoBuf.Query queries = 1;</code>
     */
     val queries: com.google.protobuf.kotlin.DslList<EcdarProtoBuf.QueryProtos.Query, QueriesProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getQueriesList()
      )
    /**
     * <pre>
     * repeated string extra i/o
     * </pre>
     *
     * <code>repeated .EcdarProtoBuf.Query queries = 1;</code>
     * @param value The queries to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addQueries")
    fun com.google.protobuf.kotlin.DslList<EcdarProtoBuf.QueryProtos.Query, QueriesProxy>.add(value: EcdarProtoBuf.QueryProtos.Query) {
      _builder.addQueries(value)
    }/**
     * <pre>
     * repeated string extra i/o
     * </pre>
     *
     * <code>repeated .EcdarProtoBuf.Query queries = 1;</code>
     * @param value The queries to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignQueries")
    inline operator fun com.google.protobuf.kotlin.DslList<EcdarProtoBuf.QueryProtos.Query, QueriesProxy>.plusAssign(value: EcdarProtoBuf.QueryProtos.Query) {
      add(value)
    }/**
     * <pre>
     * repeated string extra i/o
     * </pre>
     *
     * <code>repeated .EcdarProtoBuf.Query queries = 1;</code>
     * @param values The queries to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllQueries")
    fun com.google.protobuf.kotlin.DslList<EcdarProtoBuf.QueryProtos.Query, QueriesProxy>.addAll(values: kotlin.collections.Iterable<EcdarProtoBuf.QueryProtos.Query>) {
      _builder.addAllQueries(values)
    }/**
     * <pre>
     * repeated string extra i/o
     * </pre>
     *
     * <code>repeated .EcdarProtoBuf.Query queries = 1;</code>
     * @param values The queries to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllQueries")
    inline operator fun com.google.protobuf.kotlin.DslList<EcdarProtoBuf.QueryProtos.Query, QueriesProxy>.plusAssign(values: kotlin.collections.Iterable<EcdarProtoBuf.QueryProtos.Query>) {
      addAll(values)
    }/**
     * <pre>
     * repeated string extra i/o
     * </pre>
     *
     * <code>repeated .EcdarProtoBuf.Query queries = 1;</code>
     * @param index The index to set the value at.
     * @param value The queries to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setQueries")
    operator fun com.google.protobuf.kotlin.DslList<EcdarProtoBuf.QueryProtos.Query, QueriesProxy>.set(index: kotlin.Int, value: EcdarProtoBuf.QueryProtos.Query) {
      _builder.setQueries(index, value)
    }/**
     * <pre>
     * repeated string extra i/o
     * </pre>
     *
     * <code>repeated .EcdarProtoBuf.Query queries = 1;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearQueries")
    fun com.google.protobuf.kotlin.DslList<EcdarProtoBuf.QueryProtos.Query, QueriesProxy>.clear() {
      _builder.clearQueries()
    }}
}
@kotlin.jvm.JvmSynthetic
inline fun EcdarProtoBuf.QueryProtos.QueryRequest.copy(block: EcdarProtoBuf.QueryRequestKt.Dsl.() -> kotlin.Unit): EcdarProtoBuf.QueryProtos.QueryRequest =
  EcdarProtoBuf.QueryRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()
