//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: query.proto

package EcdarProtoBuf;

@kotlin.jvm.JvmSynthetic
inline fun query(block: EcdarProtoBuf.QueryKt.Dsl.() -> kotlin.Unit): EcdarProtoBuf.QueryProtos.Query =
  EcdarProtoBuf.QueryKt.Dsl._create(EcdarProtoBuf.QueryProtos.Query.newBuilder()).apply { block() }._build()
object QueryKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: EcdarProtoBuf.QueryProtos.Query.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: EcdarProtoBuf.QueryProtos.Query.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): EcdarProtoBuf.QueryProtos.Query = _builder.build()

    /**
     * <code>int32 id = 1;</code>
     */
    var id: kotlin.Int
      @JvmName("getId")
      get() = _builder.getId()
      @JvmName("setId")
      set(value) {
        _builder.setId(value)
      }
    /**
     * <code>int32 id = 1;</code>
     */
    fun clearId() {
      _builder.clearId()
    }

    /**
     * <code>string query = 2;</code>
     */
    var query: kotlin.String
      @JvmName("getQuery")
      get() = _builder.getQuery()
      @JvmName("setQuery")
      set(value) {
        _builder.setQuery(value)
      }
    /**
     * <code>string query = 2;</code>
     */
    fun clearQuery() {
      _builder.clearQuery()
    }

    /**
     * <code>.EcdarProtoBuf.IgnoredInputOutputs ignored_input_outputs = 3;</code>
     */
    var ignoredInputOutputs: EcdarProtoBuf.QueryProtos.IgnoredInputOutputs
      @JvmName("getIgnoredInputOutputs")
      get() = _builder.getIgnoredInputOutputs()
      @JvmName("setIgnoredInputOutputs")
      set(value) {
        _builder.setIgnoredInputOutputs(value)
      }
    /**
     * <code>.EcdarProtoBuf.IgnoredInputOutputs ignored_input_outputs = 3;</code>
     */
    fun clearIgnoredInputOutputs() {
      _builder.clearIgnoredInputOutputs()
    }
    /**
     * <code>.EcdarProtoBuf.IgnoredInputOutputs ignored_input_outputs = 3;</code>
     * @return Whether the ignoredInputOutputs field is set.
     */
    fun hasIgnoredInputOutputs(): kotlin.Boolean {
      return _builder.hasIgnoredInputOutputs()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun EcdarProtoBuf.QueryProtos.Query.copy(block: EcdarProtoBuf.QueryKt.Dsl.() -> kotlin.Unit): EcdarProtoBuf.QueryProtos.Query =
  EcdarProtoBuf.QueryKt.Dsl._create(this.toBuilder()).apply { block() }._build()
