//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: query.proto

package EcdarProtoBuf;

@kotlin.jvm.JvmSynthetic
inline fun simulationStepRequest(block: EcdarProtoBuf.SimulationStepRequestKt.Dsl.() -> kotlin.Unit): EcdarProtoBuf.QueryProtos.SimulationStepRequest =
  EcdarProtoBuf.SimulationStepRequestKt.Dsl._create(EcdarProtoBuf.QueryProtos.SimulationStepRequest.newBuilder()).apply { block() }._build()
object SimulationStepRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: EcdarProtoBuf.QueryProtos.SimulationStepRequest.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: EcdarProtoBuf.QueryProtos.SimulationStepRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): EcdarProtoBuf.QueryProtos.SimulationStepRequest = _builder.build()

    /**
     * <code>.EcdarProtoBuf.StateTuple state = 1;</code>
     */
    var state: EcdarProtoBuf.ObjectProtos.StateTuple
      @JvmName("getState")
      get() = _builder.getState()
      @JvmName("setState")
      set(value) {
        _builder.setState(value)
      }
    /**
     * <code>.EcdarProtoBuf.StateTuple state = 1;</code>
     */
    fun clearState() {
      _builder.clearState()
    }
    /**
     * <code>.EcdarProtoBuf.StateTuple state = 1;</code>
     * @return Whether the state field is set.
     */
    fun hasState(): kotlin.Boolean {
      return _builder.hasState()
    }

    /**
     * <code>.EcdarProtoBuf.Transition transition = 2;</code>
     */
    var transition: EcdarProtoBuf.ObjectProtos.Transition
      @JvmName("getTransition")
      get() = _builder.getTransition()
      @JvmName("setTransition")
      set(value) {
        _builder.setTransition(value)
      }
    /**
     * <code>.EcdarProtoBuf.Transition transition = 2;</code>
     */
    fun clearTransition() {
      _builder.clearTransition()
    }
    /**
     * <code>.EcdarProtoBuf.Transition transition = 2;</code>
     * @return Whether the transition field is set.
     */
    fun hasTransition(): kotlin.Boolean {
      return _builder.hasTransition()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun EcdarProtoBuf.QueryProtos.SimulationStepRequest.copy(block: EcdarProtoBuf.SimulationStepRequestKt.Dsl.() -> kotlin.Unit): EcdarProtoBuf.QueryProtos.SimulationStepRequest =
  EcdarProtoBuf.SimulationStepRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()
