//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: query.proto

package EcdarProtoBuf;

@kotlin.jvm.JvmSynthetic
inline fun simulationStepResponse(block: EcdarProtoBuf.SimulationStepResponseKt.Dsl.() -> kotlin.Unit): EcdarProtoBuf.QueryProtos.SimulationStepResponse =
  EcdarProtoBuf.SimulationStepResponseKt.Dsl._create(EcdarProtoBuf.QueryProtos.SimulationStepResponse.newBuilder()).apply { block() }._build()
object SimulationStepResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: EcdarProtoBuf.QueryProtos.SimulationStepResponse.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: EcdarProtoBuf.QueryProtos.SimulationStepResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): EcdarProtoBuf.QueryProtos.SimulationStepResponse = _builder.build()

    /**
     * <code>.EcdarProtoBuf.StateTuple state = 1;</code>
     */
    var state: EcdarProtoBuf.ObjectProtos.StateTuple
      @JvmName("getState")
      get() = _builder.getState()
      @JvmName("setState")
      set(value) {
        _builder.setState(value)
      }
    /**
     * <code>.EcdarProtoBuf.StateTuple state = 1;</code>
     */
    fun clearState() {
      _builder.clearState()
    }
    /**
     * <code>.EcdarProtoBuf.StateTuple state = 1;</code>
     * @return Whether the state field is set.
     */
    fun hasState(): kotlin.Boolean {
      return _builder.hasState()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    class TransitionsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated .EcdarProtoBuf.Transition transitions = 2;</code>
     */
     val transitions: com.google.protobuf.kotlin.DslList<EcdarProtoBuf.ObjectProtos.Transition, TransitionsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getTransitionsList()
      )
    /**
     * <code>repeated .EcdarProtoBuf.Transition transitions = 2;</code>
     * @param value The transitions to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addTransitions")
    fun com.google.protobuf.kotlin.DslList<EcdarProtoBuf.ObjectProtos.Transition, TransitionsProxy>.add(value: EcdarProtoBuf.ObjectProtos.Transition) {
      _builder.addTransitions(value)
    }/**
     * <code>repeated .EcdarProtoBuf.Transition transitions = 2;</code>
     * @param value The transitions to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignTransitions")
    inline operator fun com.google.protobuf.kotlin.DslList<EcdarProtoBuf.ObjectProtos.Transition, TransitionsProxy>.plusAssign(value: EcdarProtoBuf.ObjectProtos.Transition) {
      add(value)
    }/**
     * <code>repeated .EcdarProtoBuf.Transition transitions = 2;</code>
     * @param values The transitions to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllTransitions")
    fun com.google.protobuf.kotlin.DslList<EcdarProtoBuf.ObjectProtos.Transition, TransitionsProxy>.addAll(values: kotlin.collections.Iterable<EcdarProtoBuf.ObjectProtos.Transition>) {
      _builder.addAllTransitions(values)
    }/**
     * <code>repeated .EcdarProtoBuf.Transition transitions = 2;</code>
     * @param values The transitions to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllTransitions")
    inline operator fun com.google.protobuf.kotlin.DslList<EcdarProtoBuf.ObjectProtos.Transition, TransitionsProxy>.plusAssign(values: kotlin.collections.Iterable<EcdarProtoBuf.ObjectProtos.Transition>) {
      addAll(values)
    }/**
     * <code>repeated .EcdarProtoBuf.Transition transitions = 2;</code>
     * @param index The index to set the value at.
     * @param value The transitions to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setTransitions")
    operator fun com.google.protobuf.kotlin.DslList<EcdarProtoBuf.ObjectProtos.Transition, TransitionsProxy>.set(index: kotlin.Int, value: EcdarProtoBuf.ObjectProtos.Transition) {
      _builder.setTransitions(index, value)
    }/**
     * <code>repeated .EcdarProtoBuf.Transition transitions = 2;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearTransitions")
    fun com.google.protobuf.kotlin.DslList<EcdarProtoBuf.ObjectProtos.Transition, TransitionsProxy>.clear() {
      _builder.clearTransitions()
    }}
}
@kotlin.jvm.JvmSynthetic
inline fun EcdarProtoBuf.QueryProtos.SimulationStepResponse.copy(block: EcdarProtoBuf.SimulationStepResponseKt.Dsl.() -> kotlin.Unit): EcdarProtoBuf.QueryProtos.SimulationStepResponse =
  EcdarProtoBuf.SimulationStepResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()
